<div class="search-container">
    <label class="search-input-container">
        <input type="search"
               id="search-input"
               name="search"
               placeholder="Search for logs"
               aria-label="Search for logs"
               hx-get="/search"
               hx-trigger="search-trigger"
               hx-target="#search-results">
        <button id="pause-button" class="pause-button" aria-label="Pause/Resume">
            <span class="i i-pause pause-icon"></span>
            <span class="i i-play play-icon hidden"></span>
        </button>
        <button id="search-button" class="search-button" aria-label="Search" onclick="triggerSearch()">
            <span class="i i-search"></span>
            <span class="notification-dot hidden"></span>
        </button>
        <button id="clear-logs-button" class="clear-button" aria-label="Clear logs" onclick="clearLogs()">
            <span class="i i-trash"></span>
        </button>
    </label>
</div>