[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [Unreleased]
"""
body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
{% for commit in commits %}
- {{ commit.message | upper_first }}{% if commit.breaking %} (BREAKING){% endif %}
{% endfor %}
{% endfor %}
"""
trim = true
postprocessors = [{ pattern = "Other", replace = "Changed" }]

[git]
conventional_commits = true
filter_unconventional = false
commit_parsers = [
    { message = "^feat", group = "Added" },
    { message = "^fix", group = "Fixed" },
    { message = "^docs", group = "Documentation" },
    { message = "^test", group = "Test" },
    { message = "^refactor", group = "Changed" },
    { message = "^style", group = "Style" },
    { message = "^chore", group = "Maintenance" },
    { message = "^perf", group = "Performance" },
    { message = "^ci", group = "CI/CD" },
    { message = ".*", group = "Other" },
]
