<?php foreach ($this->entries as $entry) : ?>
    <?php $flattenWithDotsentry = $this->flattenWithDots($entry); ?>
    <div class="log-entry">
        <div class="log-header" _="on click toggle .collapsed on next .log-content then toggle .rotate-180 on first in me">
            <button>
                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" width="16">
                    <path
                        fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                        clip-rule="evenodd"
                    />
                </svg>
            </button>
            <span class="datetime"><?= $this->escape($entry['datetime']) ?></span>
            <span class="channel">[<?= $this->escape($entry['channel']) ?>]</span>
            <span class="level <?= strtolower($entry['level']) ?>"><?= $this->escape($entry['level']) ?></span>
            <span class="message"><?= $this->escape($entry['message']) ?></span>
        </div>
        <div class="log-content collapsed">
            <?= $this->partial('search/partials/item', ['entry' => $flattenWithDotsentry]) ?>
        </div>
    </div>
<?php endforeach; ?>
