<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?= $this->title ?></title>
    <link rel="icon" type="image/x-icon" href="/favicon.ico">
    <script src="/htmx.min.js"></script>
    <script src="/htmx-ext-sse.js"></script>
    <script src="/hyperscript.min.js"></script>
    <link rel="stylesheet" href="/assets/icons/icons.css">
    <link rel="stylesheet" href="/styles.css">
    <script src="/scripts.js" defer></script>
</head>
<body hx-indicator="body">
<a href="#main-content" class="sr-only focusable">Skip to main content</a>
<div id="live-status" class="sr-only" aria-live="polite" aria-atomic="true"></div>
<main id="main-content" class="container">
    <div id="progress-bar"></div>
    <header>
        <h1><?= $this->header ?></h1>
        <button id="theme-toggle" class="theme-toggle" aria-label="Theme toggle">
            <span class="i i-sun sun"></span>
            <span class="i i-moon moon"></span>
        </button>
    </header>
    <div class="controls">
        <?= $this->slot ?>
    </div>

    <div id="search-results" hx-ext="sse" sse-connect="/logs-stream" sse-swap="message"></div>
</main>
</body>
</html>