name: check

on:
  pull_request:

jobs:

  code-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Composer Downloads
        uses: actions/cache@v4
        with:
          path: vendor/
          key: ${{ runner.OS }}-composer-${{ hashFiles('**/composer.lock') }}

      - name: Build development image
        run: make image

      - name: Composer install
        run: make install

      - name: Run linter
        run: make phpcs

  code-static-analyse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Composer Downloads
        uses: actions/cache@v4
        with:
          path: vendor/
          key: ${{ runner.OS }}-composer-${{ hashFiles('**/composer.lock') }}

      - name: Build development image
        run: make image

      - name: Composer install
        run: make install

      - name: Run static analyse
        run: make phpstan

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Composer Downloads
        uses: actions/cache@v4
        with:
          path: vendor/
          key: ${{ runner.OS }}-composer-${{ hashFiles('**/composer.lock') }}

      - name: Build development image
        run: make image

      - name: Composer install
        run: make install

      - name: Run unit tests
        run: make test
